// GENERATED by tool/build.dart. Do not edit.
//
// What the binaries answer when they are asked which version they are. A build is told its tag in
// the ANSIWISE_RELEASE_TAG environment variable and this file is how that value reaches the
// compiler; a build nobody told stamps "unreleased".
//
// It is here rather than in the version a manifest declares because a manifest states three numbers
// and a release is <major>.<minor>.<patch>-<channel>-<ts14>: the channel and the stamp are what a
// pin is written with, and a comparison against three numbers alone would never match one.
library;

/// The release this binary was built at, or `unreleased` for a build that was told no tag.
///
/// EVERY READER OF A PLACED BINARY ASKS THIS. It is what `--version` answers, what a pinned-tool
/// step compares against the pin it carries, and therefore what decides whether a machine is left
/// alone or fetched again.
const String releaseStamp = 'unreleased';
